on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Start Minecraft server
        run: |
          cd AdventuresInMinecraft-Linux-master/Server
          chmod +x ./start.sh
          cd ..
          chmod +x ./StartServer.sh
          echo | ./StartServer.sh &
          sleep 20
        shell: bash

      - name: Start Pyro4 naming server
        run: |
          cd AdventuresInMinecraft-Linux-master/minecraft_agent_framework/Pyro4
          python -m Pyro4.naming &  # Iniciar el servidor de nombres de Pyro4 en segundo plano
          sleep 5  # Esperar a que el servidor de nombres se inicie

      - name: Start bot server de Pyro4
        run: |
          cd AdventuresInMinecraft-Linux-master/minecraft_agent_framework/Pyro4
          python botServer.py &  # Iniciar el servidor Pyro4 del bot en segundo plano
          sleep 5  # Esperar a que el servidor del bot se inicie

      - name: Test with pytest
        timeout-minutes: 3
        continue-on-error: true
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest AdventuresInMinecraft-Linux-master/minecraft_agent_framework/tests/ --cov=AdventuresInMinecraft-Linux-master/minecraft_agent_framework --cov-report=xml

      - name: Stop background processes
        run: |
          pkill -f StartServer.sh || echo "Minecraft server not running"
          pkill -f Pyro4.naming || echo "Pyro4 naming server not running"
          pkill -f botServer.py || echo "Bot server not running"
        shell: bash

      - name: Check coverage file
        run: |
          ls -la coverage.xml
          cat coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: SerbFlorian/TAP_Minecraft
          files: ./coverage.xml
          fail_ci_if_error: true
